name: RollemPro
favicon: null
layout_spectrum: 0.24468
typography_spectrum: 0.09318996
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Roll'em Productions"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94A9BA'
    - '#010102'
    - '#FFFEFF'
    - '#4B555E'
    - '#303031'
  brandStrength: 0.625
  lightness: 0.6971326
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
